export const SEARCH_ANIMAL_REQUEST = 'SEARCH_ANIMAL_REQUEST';
export const SEARCH_ANIMAL_SUCCESS = 'SEARCH_ANIMAL_SUCCESS';
export const SEARCH_ANIMAL_FAILURE = 'SEARCH_ANIMAL_FAILURE';

export const GET_ANIMALS_REQUEST = 'GET_ANIMALS_REQUEST';
export const GET_ANIMALS_SUCCESS = 'GET_ANIMALS_SUCCESS';
export const GET_ANIMALS_FAILURE = 'GET_ANIMALS_FAILURE';

export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';

export const SET_CURRENT_ANIMAL = 'SET_CURRENT_ANIMAL';
export const CHANGE_PAGE = 'CHANGE_PAGE';